### ISSUE TITLE
Change port in config.toml

### ISSUE THREAD

**Issue by rehod** [s0up4200/redactedhook#31]
Is there a possibility to change the port of redactedhook in the config.toml? I have a seedhost shared seedbox and there  I get the error:
FTL Failed to start server error="listen tcp 127.0.0.1:42135: bind: address already in use" Maybe there is someone else on the same box using it or something. 

I can't use docker to build.

**Comment by s0up4200** [comment]
Hi! Yes it will be possible in the next version. There is a PR up with that feature in it. I should merge that soon. Will let you know!

**Comment by rehod** [comment]
Thanks for the answer. How soon do you think it will be? I'm asking because I've bought this seedbox for 30 days. Should I cancel it?

**Comment by s0up4200** [comment]
> Thanks for the answer. How soon do you think it will be? I'm asking because I've bought this seedbox for 30 days. Should I cancel it?

I'll try to make a new release for you tonight👍

**Comment by rehod** [comment]
This would be amazing, thanks!

**Comment by s0up4200** [comment]
New release published. Hopefully no bugs 😄 I can't dedicate time to fix those right now.

**Comment by rehod** [comment]
Thanks for the super quick fix. Last question how to config this in the config.toml. 
host = "127.0.0.1"
port = "42316"
Does not work.

**Comment by rehod** [comment]
2024-06-01 18:42:38 DBG Config file read: config.toml
2024-06-01 18:42:38 INF Starting server on 127.0.0.1:42136
2024-06-01 18:42:38 INF Version: 0.5.0, Commit: 2ca8a0cb6da4e82bffa27733f1e87aea5f309623, Build Date: unknown

This worked. Thanks so much.

**Comment by s0up4200** [comment]
Awesome! Happy to help👍
